[package]
name = "nitori_core"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wmi = "0.13.1"
serde_json = "1.0.108"

[lib]
crate_type = ["dylib"]
name = "nitori_core"