# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Build Application

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'lib/**'
      - 'nitori_core/**'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
 build:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v3
     - name: Build Core
       run: cargo build --release
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
     - name: Build Application
       run: |
        flutter config --enable-windows-desktop
        flutter build windows
        ls
        cp README.md build/windows/runner/Release/
        ls target/release
        cp target/release/nitori_core.dll build/windows/runner/Release/
     - name: Upload Artifact
       uses: actions/upload-artifact@v3.1.2
       with:
         name: NitoriToolbox
         path: 'build/windows/runner/Release/*'
